### ISSUE TITLE
Invoices get Overdue instead of TODO status

### ISSUE THREAD

**Issue by LaurensVanAcker** [invoiceninja/ui#533] opened 2023-03-14 20:20 UTC
In v**8/3/23** the invoice list shows all old invoices with the status **"Overdue"**.
If you browse a detail page of a customer and open the tab invoices, they get correctly tagged as **Paid**.

The Flutter interface shows it correctly.

If you filter on **Unpaid** in the invoice list, you also get those old **Paid** invoices.

**Comment by turbo124** [comment] 2023-03-14 22:34
@LaurensVanAcker 

The issue is fixed in the API, will be available in the next release.

**Closed** 2023-03-15 22:48 UTC
