### ISSUE TITLE
Default Tax Rate issues

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/ui#952] opened 2023-07-13 13:49 UTC
![image](https://github.com/invoiceninja/invoiceninja/assets/13354331/a31ad8b1-0c6c-492d-87e4-f40304b61f48)

## Setup
- Version: 5.1
- Environment: Kubernetes

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? no
- Have you searched existing issues? yes
- Have you reported this to Slack/forum before posting? no
- Have you inspected the logs in storage/logs/laravel.log for any errors? no

## Describe the bug
When selecting the default tax rates, I get many unexpected options, which probably once existed and have been deleted.
Also, if I select 19% it is applied correctly in invoices, but still displays 0% there.

### Expected Behavior
Only the active rates are available.

**Comment by turbo124** [comment] 2023-07-16 21:33
A fix has been checked in for this, it should be available in .19 or .20 (when tagged)

**Comment by LaurensVanAcker** [comment] 2023-09-17 10:19
![image](https://github.com/invoiceninja/ui/assets/4385000/142bded3-1739-46b9-9aee-610d9a453316)
We are facing similar issues: the amount due is incorrect and we need to select 6% to get 21% VAT in the PDF.

Tested with **15.09.2023.1**

**Comment by turbo124** [comment] 2023-09-18 01:26
Are you able to share the full invoice items so that we can attempt to recreate this please.

we just need to quantity / unit cost / tax rate / discount

then we can write the tests against this scenario.

it would also help if you tested here: https://react.invoicing.co as this has the latest changes that are in the queue for release.

**Comment by LaurensVanAcker** [comment] 2023-09-18 10:00
![ezgif-5-775351cc8f](https://github.com/invoiceninja/ui/assets/4385000/4d8b5604-fa6f-410c-9ba1-1e2ad65d14bf)
Yes, I can reproduce this on the demo site. In the video, you see it jumps to 21% when I select 6%. At the bottom, you also see no VAT is applied in the PDF when selecting 6%, even while the dropdown has 21%.

So the dropdown shows something else then selected and the PDF percentage doesn't match the dropdown. It even leaves out VAT.

**Comment by LaurensVanAcker** [comment] 2023-09-18 10:56
It's probably when two tax lines have the same name. But the percentage is added, so it's hard to make them unique, or you get like "VAT 21% 21%".

**Comment by turbo124** [comment] 2023-09-18 21:45
@LaurensVanAcker 

I've noticed recently that our production builds are not correctly bundling the latest version of the react application. I think that _may_ be the issue here. Can you advise how you are installing the app?

**Comment by LaurensVanAcker** [comment] 2023-09-19 17:01
I have built a custom Dockerfile because I combine Nginx with HTTP in one container, and I was not too fond of the one proposed.

I update the backend by pointing the GIT submodule to a version TAG. And the frontend by opening https://api.github.com/repos/invoiceninja/ui/releases/latest, searching for "-react.zip" and manually coping that URL in the Dockerfile (the date changes).

So, it uses the same ZIP as your production server, and it uses the React version that comes with the IN repo package file.
[Dockerfile.txt](https://github.com/invoiceninja/ui/files/12664588/Dockerfile.txt)

**Comment by turbo124** [comment] 2023-09-21 03:55
Ok, I see the issue now.

The bug here is that you were able to update a tax rate name to match another tax rates name. This breaks the way we aggregate the taxes.

You'll want to prefix your reduced tax rate BTW [r] or similar to create a unique name. I've checked in a fix to ensure that the tax names cannot be duplicated.

**Comment by turbo124** [comment] 2023-09-21 03:56
Fixed in API here:

https://github.com/invoiceninja/invoiceninja/pull/8822

**Closed by turbo124** 2023-09-21 03:56 UTC
Labels: bug
